package t5;
// Generated 21/01/2013 16:33:01 by Hibernate Tools 3.2.1.GA

import entidades.*;




/**
 * Cliente_bak generated by hbm2java
 */
public class Cliente_bak  implements java.io.Serializable {


     private Integer idCliente;
     private String login;
     private String senha;
     private String frase;
     private String nome;
     private String endereco;
     private String cep;
     private Integer reputacao;
     private Boolean adm;
     private Boolean admPrinc;

    public Cliente_bak() {
    }

	
    public Cliente_bak(String cep) {
        this.cep = cep;
    }
    public Cliente_bak(String login, String senha, String frase, String nome, String endereco, String cep, Integer reputacao, Boolean adm, Boolean admPrinc) {
       this.login = login;
       this.senha = senha;
       this.frase = frase;
       this.nome = nome;
       this.endereco = endereco;
       this.cep = cep;
       this.reputacao = reputacao;
       this.adm = adm;
       this.admPrinc = admPrinc;
    }
   
    public Integer getIdCliente() {
        return this.idCliente;
    }
    
    public void setIdCliente(Integer idCliente) {
        this.idCliente = idCliente;
    }
    public String getLogin() {
        return this.login;
    }
    
    public void setLogin(String login) {
        this.login = login;
    }
    public String getSenha() {
        return this.senha;
    }
    
    public void setSenha(String senha) {
        this.senha = senha;
    }
    public String getFrase() {
        return this.frase;
    }
    
    public void setFrase(String frase) {
        this.frase = frase;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public String getEndereco() {
        return this.endereco;
    }
    
    public void setEndereco(String endereco) {
        this.endereco = endereco;
    }
    public String getCep() {
        return this.cep;
    }
    
    public void setCep(String cep) {
        this.cep = cep;
    }
    public Integer getReputacao() {
        return this.reputacao;
    }
    
    public void setReputacao(Integer reputacao) {
        this.reputacao = reputacao;
    }
    public Boolean getAdm() {
        return this.adm;
    }
    
    public void setAdm(Boolean adm) {
        this.adm = adm;
    }
    public Boolean getAdmPrinc() {
        return this.admPrinc;
    }
    
    public void setAdmPrinc(Boolean admPrinc) {
        this.admPrinc = admPrinc;
    }




}


